### ISSUE TITLE
Add Import Validation for Emissions Data Codes

### ISSUE THREAD

**Issue by AmandaMNelson** [US-EPA-CAMD/easey-ecmps-ui#1020] opened 2023-04-13 20:43 UTC
When a user imports an emissions file where a code (spanScaleCode, testResultCode, gasLevelCode, etc.) is not valid,
an import check validation message should appear, directing them to enter a valid code.

Should the response message include a list of valid codes?

Should this be covered under an existing Import check? (17?)

**Comment by JanellC** [comment] 2023-05-16 15:01
Need confirmation if this bug is valid @acollad1

**Comment by jwhitehead77** [comment] 2023-05-16 23:39
duplicate of #5096

**Closed as completed by jwhitehead77** 2023-05-16 23:39 UTC
Labels: bug, Emissioners  Emissions
